remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # You can change this to "dark", "contrast", or "aqua" later!

# Site Settings
title: "Ampa Ranjan"
name: "Ampa Ranjan"
description: "B.Tech CSE @ KIIT | BS Data Science @ IIT Madras"
url: "https://ampaKR0711.github.io"
locale: "en-US"

# Author Settings
author:
  name: "Ampa Ranjan"
  avatar: "/assets/images/bio-photo.jpg" # We will upload this later
  bio: "3rd Year CSE @ KIIT | IIT Madras BS Candidate | AI Researcher"
  location: "Bhubaneswar, India"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://in.linkedin.com/in/ampa-ranjan-21749338a"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ampaKR0711"

# Defaults for Layouts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
