# Site Settings
title: "Ampa Ranjan"
description: "B.Tech CSE @ KIIT | BS Data Science @ IIT Madras"
url: "https://ampakr0711.github.io"

# Author Settings
author:
  name: "Ampa Ranjan"
  bio: "3rd Year CSE Student at KIIT University and Data Science Candidate at IIT Madras. Focused on Agentic AI and Financial Data Engineering."
  location: "Bhubaneswar, India"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://in.linkedin.com/in/ampa-ranjan-21749338a"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ampaKR0711"
