remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"

# Site Settings
title: "Ampa Ranjan"
url: "https://ampaKR0711.github.io"
locale: "en-US"

# Sidebar Info
author:
  name: "Ampa Ranjan"
  bio: "3rd Year CSE @ KIIT | IIT Madras BS Candidate | AI Researcher"
  location: "Bhubaneswar, India"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://in.linkedin.com/in/ampa-ranjan-21749338a"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ampaKR0711"

# Layout Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true
